import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import { cookies } from "next/headers";
import { jwtVerify } from "jose";
import HeaderLogado from "../components/HeaderLogado";
import Header from "../components/Header/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "700"],
}); 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function usuarioLogado() {
  const cookieStore = await cookies();
  const token = cookieStore.get("session_token")?.value;

  if (!token) return false;

  try {
    const SECRET_KEY = new TextEncoder().encode(
      process.env.JWT_SECRET || 'chave-ultra-secreta-daora123'
    );
    await jwtVerify(token, SECRET_KEY);
    return true; 
  } catch (error) {
    return false; 
  }
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const estaLogado = await usuarioLogado();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} antialiased`}
      >
        {estaLogado ? <HeaderLogado /> : <Header />}
        {children}
      </body>
    </html>
  );
}
